name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your default branch is (e.g., master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install dependencies ⬇
        run: npm install

      - name: Build 
        run: npm run build

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # This is the crucial part! Change to ./build if using Create React App
          cname: teamtails.org 
          # full_deploy: true # Use this if you want to completely replace content, otherwise it appends
